name: Deploy CarChuno UI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          ref: ${{ github.head_ref }}
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: Install Packages
        run: npm install
      - name: Deploy to GH Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "shindetejas2011@gmail.com"
          git config --global user.name "nyt-owls"
          npm run deploy
